UBUNTU: [Config] ibm-gt: Enable CONFIG_NET_SWITCHDEV=y for s390x
This config option is required so that CONFIG_MLX5_ESWITCH=y is set
which in turn is required by the previously applied IBM/Mellanox
patchset. Otherwise we'll get an s390x compilation error:

drivers/net/ethernet/mellanox/mlx5/core/fs_core.c: In function 'init_fdb_root_ns':
drivers/net/ethernet/mellanox/mlx5/core/fs_core.c:2485:12: error: 'FDB_MAX_CHAIN' undeclared (first use in this function); did you mean '__MAX_CHPID'?
            FDB_MAX_CHAIN+1, GFP_KERNEL);
            ^~~~~~~~~~~~~
            __MAX_CHPID

Signed-off-by: Juerg Haefliger <juergh@canonical.com>